- type: entity
  abstract: true
  id: CameraStrapSlotBase
  components:
  - type: ItemSlots
    slots:
      camera_strap:
        name: clothing-security-uniform-camera-strap-slot
        renderSlot: neck
        whitelist:
          tags:
          - BodyCamera